# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 2
name = "Default starter for Rust"
service_id = "qk7qluLoJRpggi0XNr5694"

[local_server]
    [local_server.backends]
        [local_server.backends.mioriente]
            override_host = "mioriente-new.sindyk.com"
            url = "http://35.199.15.132:80"

[setup]
    [setup.backends]
        [setup.backends.mioriente]
            override_host = "mioriente-new.sindyk.com"
            address = "35.199.15.132"
            port = 80